[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true, features = ["document"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.217"
